spring.datasource.url: jdbc:h2:file:./camunda-h2-database

spring.flyway.url: jdbc:h2:file:./camunda-h2-database

spring.datasource.driverClassName: org.h2.Driver
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.H2Dialect

spring.h2.console.enabled: true

spring.flyway.baseline-on-migrate: true
server.port: 8081

camunda:
  bpm:
    deployment-resource-pattern: classpath*:processes/trainer_processes/*.*
    metrics:
      enabled: false
    historyCleanupmetricsEnabled: false


camunda.bpm.admin-user:
  id: demo
  password: demo



camunda.bpm.client:
  base-url: http://localhost:8081/engine-rest
  subscriptions:
    getFact:
      include-extension-properties: true

camunda.bpm.job-execution:
  lock-time-in-millis: 20000
  wait-time-in-millis: 1
  max-wait: 1